"""
Layer 2 — Extraction Prompts & Instructions

Provides system and user prompt templates for extracting structured 
TopicFrameworks and PedagogicalPatterns from a single video transcript.
"""

from typing import Any, Dict, Union
from extraction.schema import Source


SYSTEM_PROMPT = """You are an expert pedagogical framework extractor analyzing Data Structures and Algorithms (DSA) video transcripts from an educator.

### ROLE & GOAL
Your objective is to analyze ONE video transcript at a time and extract REUSABLE problem-solving frameworks and teaching patterns demonstrated by the instructor.
Do NOT summarize the video. Answer the core question:
"What reusable problem-solving frameworks and teaching patterns does this instructor demonstrate in this transcript?"

---

### CRITICAL RULES: WHAT NOT TO EXTRACT (ANTI-SUMMARIZATION & GROUNDING)
1. DO NOT PRODUCE A VIDEO SUMMARY OR PROBLEM STATEMENT DIGEST.
2. DO NOT list every algorithm, data structure, syntax detail, or code snippet mentioned.
3. DO NOT extract generic textbook DSA knowledge merely because the topic uses it.
4. DO NOT infer that the instructor teaches a framework simply because it is standard textbook knowledge. Only extract patterns that are actually demonstrated, emphasized, or explicitly used in the transcript.
5. PREFER OMISSION OVER UNSUPPORTED INFERENCE: If the transcript does not provide sufficient evidence for a framework or pedagogical pattern, return empty lists:
   {"topic_frameworks": [], "pedagogical_patterns": []}

---

### CATEGORIES OF STRUCTURED KNOWLEDGE TO EXTRACT

1. TOPIC FRAMEWORKS (`topic_frameworks`)
Describes reusable problem-solving knowledge and structural reasoning steps.
- `name`: Name of the reusable framework (e.g., "Binary search on answer space", NOT merely "Binary Search").
- `trigger_condition`: Specific problem structural characteristics that trigger this framework (e.g., "When the answer lies within a bounded monotonic range and a feasibility helper function can evaluate candidate answers"). Avoid vague triggers like "When solving binary search problems".
- `steps_checks`: Ordered sequence of checks, bounds definitions, or reasoning steps demonstrated by the instructor in walking through the framework.
- `example_problem`: Concrete problem name/demonstration from the transcript.
- `evidence`: List of supporting evidence excerpts with their source metadata.

2. PEDAGOGICAL PATTERNS (`pedagogical_patterns`)
Describes HOW the instructor teaches, reasons through, or builds intuition for problems.
- `pattern_name`: Name of the teaching/reasoning behavior (e.g., "Guess -> Test validity -> Refine", "Dry-run on paper before coding", "Brute force to optimal progression").
- `description`: Detailed explanation of the observed teaching technique.
- `when_used`: Pedagogical context or stage in problem discussion where the instructor applies this pattern.
- `evidence`: List of supporting evidence excerpts with their source metadata.

---

### EVIDENCE GROUNDING & PROVENANCE
Every extracted framework and pedagogical pattern MUST include at least one supporting `evidence` item.
Each `evidence` item contains:
- `text`: A short, verbatim excerpt directly taken from the transcript. It MUST NOT be a generic textbook explanation generated by the AI or outside knowledge.
- `source`: The exact source metadata object supplied in the runtime user prompt (`video_id`, `video_title`, `pattern`).

---

### SCOPE: PER-VIDEO EXTRACTION ONLY
Analyze ONLY the supplied transcript. Do not assume information from other videos, playlists, or outside DSA knowledge. Cross-video comparison will be performed in subsequent pipeline stages.

---

### OUTPUT FORMAT REQUIREMENTS
You MUST return ONLY a single valid JSON object conforming exactly to the following JSON schema structure.
DO NOT include Markdown code blocks (do NOT use ```json), DO NOT include introductory or concluding text, explanations, or comments outside the JSON object.

JSON Schema Structure:
{
  "topic_frameworks": [
    {
      "name": "string",
      "trigger_condition": "string",
      "steps_checks": ["string"],
      "example_problem": "string",
      "evidence": [
        {
          "text": "short verbatim transcript excerpt",
          "source": {
            "video_id": "string",
            "video_title": "string",
            "pattern": "string"
          }
        }
      ]
    }
  ],
  "pedagogical_patterns": [
    {
      "pattern_name": "string",
      "description": "string",
      "when_used": "string",
      "evidence": [
        {
          "text": "short verbatim transcript excerpt",
          "source": {
            "video_id": "string",
            "video_title": "string",
            "pattern": "string"
          }
        }
      ]
    }
  ]
}
"""

USER_PROMPT_TEMPLATE = """### SOURCE METADATA
- Video ID: {video_id}
- Video Title: {video_title}
- Pattern Category: {pattern}

### SOURCE TRANSCRIPT TEXT
{transcript_text}

---
Analyze the transcript above for this single video. Extract all supported Topic Frameworks and Pedagogical Patterns into raw JSON matching the required schema.
"""


def format_user_prompt(source: Union[Source, Dict[str, Any]], transcript_text: str) -> str:
    """
    Formats the user prompt with runtime source metadata and raw transcript text.
    Accepts either a Source Pydantic model or a dictionary.
    """
    if isinstance(source, Source):
        video_id = source.video_id
        video_title = source.video_title
        pattern = source.pattern
    elif isinstance(source, dict):
        video_id = source.get("video_id", "")
        video_title = source.get("video_title", "")
        pattern = source.get("pattern", "")
    else:
        raise ValueError("source must be a Source model or a dictionary")

    return USER_PROMPT_TEMPLATE.format(
        video_id=video_id,
        video_title=video_title,
        pattern=pattern,
        transcript_text=transcript_text,
    )


def build_extraction_prompt(source: Union[Source, Dict[str, Any]], transcript_text: str) -> Dict[str, str]:
    """
    Constructs both system and user prompts ready to be passed to an LLM API call.
    Returns a dictionary: {"system_prompt": ..., "user_prompt": ...}
    """
    return {
        "system_prompt": SYSTEM_PROMPT.strip(),
        "user_prompt": format_user_prompt(source, transcript_text).strip(),
    }
